package org.wangxiaolang.serviceprovider.entity;

import com.baomidou.mybatisplus.annotation.TableName;

import java.util.Date;

@TableName(value = "permissions")
public class PermissionsDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.id
     *
     * @mbg.generated Thu Dec 05 14:25:02 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.name
     *
     * @mbg.generated Thu Dec 05 14:25:02 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.description
     *
     * @mbg.generated Thu Dec 05 14:25:02 CST 2024
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.created_at
     *
     * @mbg.generated Thu Dec 05 14:25:02 CST 2024
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.id
     *
     * @return the value of permissions.id
     *
     * @mbg.generated Thu Dec 05 14:25:02 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.id
     *
     * @param id the value for permissions.id
     *
     * @mbg.generated Thu Dec 05 14:25:02 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.name
     *
     * @return the value of permissions.name
     *
     * @mbg.generated Thu Dec 05 14:25:02 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.name
     *
     * @param name the value for permissions.name
     *
     * @mbg.generated Thu Dec 05 14:25:02 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.description
     *
     * @return the value of permissions.description
     *
     * @mbg.generated Thu Dec 05 14:25:02 CST 2024
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.description
     *
     * @param description the value for permissions.description
     *
     * @mbg.generated Thu Dec 05 14:25:02 CST 2024
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.created_at
     *
     * @return the value of permissions.created_at
     *
     * @mbg.generated Thu Dec 05 14:25:02 CST 2024
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.created_at
     *
     * @param createdAt the value for permissions.created_at
     *
     * @mbg.generated Thu Dec 05 14:25:02 CST 2024
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}