package org.wangxiaolang.serviceprovider.entity;

import com.baomidou.mybatisplus.annotation.TableName;

import java.util.Date;

@TableName(value = "roles")
public class RolesDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.id
     *
     * @mbg.generated Thu Dec 05 14:23:59 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.name
     *
     * @mbg.generated Thu Dec 05 14:23:59 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.description
     *
     * @mbg.generated Thu Dec 05 14:23:59 CST 2024
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.created_at
     *
     * @mbg.generated Thu Dec 05 14:23:59 CST 2024
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.id
     *
     * @return the value of roles.id
     *
     * @mbg.generated Thu Dec 05 14:23:59 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.id
     *
     * @param id the value for roles.id
     *
     * @mbg.generated Thu Dec 05 14:23:59 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.name
     *
     * @return the value of roles.name
     *
     * @mbg.generated Thu Dec 05 14:23:59 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.name
     *
     * @param name the value for roles.name
     *
     * @mbg.generated Thu Dec 05 14:23:59 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.description
     *
     * @return the value of roles.description
     *
     * @mbg.generated Thu Dec 05 14:23:59 CST 2024
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.description
     *
     * @param description the value for roles.description
     *
     * @mbg.generated Thu Dec 05 14:23:59 CST 2024
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.created_at
     *
     * @return the value of roles.created_at
     *
     * @mbg.generated Thu Dec 05 14:23:59 CST 2024
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.created_at
     *
     * @param createdAt the value for roles.created_at
     *
     * @mbg.generated Thu Dec 05 14:23:59 CST 2024
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}